const PRODUCTS = [
  {
    id: "pack-1",
    name: "Nom du pack",
    price: 300,
    image: "../image/image1.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-2",
    name: "Nom du pack",
    price: 300,
    image: "../image/image2.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-3",
    name: "Nom du pack",
    price: 300,
    image: "../image/image3.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-4",
    name: "Nom du pack",
    price: 300,
    image: "../image/image4.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-5",
    name: "Nom du pack",
    price: 300,
    image: "../image/image5.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-6",
    name: "Nom du pack",
    price: 300,
    image: "../image/image6.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-7",
    name: "Nom du pack",
    price: 300,
    image: "../image/image7.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-8",
    name: "Nom du pack",
    price: 300,
    image: "../image/image8.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-9",
    name: "Nom du pack",
    price: 300,
    image: "../image/image9.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
  {
    id: "pack-10",
    name: "Nom du pack",
    price: 300,
    image: "../image/image10.jpg",
    color: "blue",
    short: "Courte description (1 phrase, affichée sur la carte).",
    description: "Description longue et détaillée, affichée sur la page produit.",
    sheets: "1 planche — 00 stickers",
    format: "PDF haute résolution — A4, prêt à imprimer",
  },
];